[package]
name = "gpm"
version = "0.1.9"
authors = ["Axetroy <axetroy.dev@gmail.com>"]
readme = "README.md"
keywords = ["gpm", "git", "project", "manager"]
repository = "https://github.com/axetroy/gpm.rs"
description = """
A command line tool, manage your hundreds of repository, written with Rust.
"""

edition = "2021"

[[bin]]
name = "gpm"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.2"
git-url-parse = "0.4.0"
ctrlc = { version = "3.2.1", features = ["termination"] }
dirs = "1.0.4"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
inquire = { version = "0.2.1" }
eyre = "0.6.7"
path-absolutize = "3.0.11"