[package]
name = "github.com/axetroy/gpm.rs"
bin = "gpm"
authors = ["Axetroy <axetroy.dev@gmail.com>"]
keywords = ["gpm", "git", "project", "manager"]
repository = "https://github.com/axetroy/gpm.rs"
description = """
A command line tool, manage your hundreds of repository, written with Rust.
"""
license = "MIT"

[darwin]
x86_64 = { url = "https://github.com/axetroy/gpm.rs/releases/download/v{version}/gpm_darwin_amd64.tar.gz" }
aarch64 = { url = "https://github.com/axetroy/gpm.rs/releases/download/v{version}/gpm_darwin_arm64.tar.gz" }

[windows]
x86 = { url = "https://github.com/axetroy/gpm.rs/releases/download/v{version}/gpm_windows_386.tar.gz" }
x86_64 = { url = "https://github.com/axetroy/gpm.rs/releases/download/v{version}/gpm_windows_amd64.tar.gz" }
aarch64 = { url = "https://github.com/axetroy/gpm.rs/releases/download/v{version}/gpm_windows_arm64.tar.gz" }

[linux]
x86 = { url = "https://github.com/axetroy/gpm.rs/releases/download/v{version}/gpm_linux_386.tar.gz" }
x86_64 = { url = "https://github.com/axetroy/gpm.rs/releases/download/v{version}/gpm_linux_amd64.tar.gz" }
aarch64 = { url = "https://github.com/axetroy/gpm.rs/releases/download/v{version}/gpm_linux_arm64.tar.gz" }
mips = { url = "https://github.com/axetroy/gpm.rs/releases/download/v{version}/gpm_linux_mips.tar.gz" }
mips64 = { url = "https://github.com/axetroy/gpm.rs/releases/download/v{version}/gpm_linux_mips64.tar.gz" }
mips64el = { url = "https://github.com/axetroy/gpm.rs/releases/download/v{version}/gpm_linux_mips64el.tar.gz" }
