# NOTE: Custom image specification for freebsd is required until new version of cross is released.
[target.x86_64-unknown-freebsd]
image = "svenstaro/cross-x86_64-unknown-freebsd:latest"

[build.env]
passthrough = [
    "CARGO_INCREMENTAL",
    "RUST_BACKTRACE",
    "CARGO_TERM_COLOR",
]