[target.x86_64-unknown-linux-musl]
rustflags = [ "-C", "target-feature=+crt-static" ]

[target.i686-unknown-linux-musl]
rustflags = [ "-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"
rustflags = [ "-C", "target-feature=+crt-static", "-C", "link-arg=-lgcc"]

[target.mips-unknown-linux-gnu]
linker = "mips-linux-gnu-gcc"
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-lgcc"]

[target.mips64-unknown-linux-gnuabi64]
linker = "mips64-linux-gnuabi64-gcc"
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-lgcc"]

[target.mips64el-unknown-linux-gnuabi64]
linker = "mips64el-linux-gnuabi64-gcc"
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-lgcc"]

[target.x86_64-apple-darwin]
rustflags = [ "-C", "target-feature=+crt-static" ]

[target.aarch64-apple-darwin]
rustflags = [ "-C", "target-feature=+crt-static" ]

[target.x86_64-pc-windows-msvc]
rustflags = [ "-C", "target-feature=+crt-static" ]

[target.i686-pc-windows-msvc]
rustflags = [ "-C", "target-feature=+crt-static" ]

[target.aarch64-pc-windows-msvc]
rustflags = [ "-C", "target-feature=+crt-static" ]